server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: order-stream

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_service_db}
    username: ${DB_USERNAME:order}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}

  flyway:
    locations: classpath:db/migrations
    enabled: true

websocket:
  allowed-origins: ${WS_ALLOWED_ORIGINS:http://localhost:63342,http://localhost:8080}
  broker-destination-prefix: ${WS_BROKER_PREFIX:/topic}
  application-destination-prefix: ${WS_APP_PREFIX:/app}
  user-destination-prefix: ${WS_USER_PREFIX:/user}
  endpoint: ${WS_ENDPOINT:/ws}
  raw-endpoint: ${WS_RAW_ENDPOINT:/ws-raw}